"""
Report generator: incident report, audit packet, NIST mapping, PDF export.
Uses Claude for the narrative sections and ReportLab for PDF rendering.
"""
from datetime import datetime, timezone
from .nist_mapper import NistMapper, NIST_FUNCTIONS


class ReportGenerator:
    def __init__(self, case, user):
        self.case = case
        self.user = user

    def incident_report(self) -> dict:
        from flask import current_app
        from .ai_analyst import AIAnalyst

        analysis = {}
        try:
            analyst = AIAnalyst()
            analysis = analyst.analyze_case(self.case)
        except Exception:
            pass

        timeline_entries = [
            {
                "time": t.event_time.isoformat(),
                "type": t.event_type,
                "description": t.description,
                "source": t.source,
            }
            for t in (self.case.timeline or [])
        ]

        entities = [e.to_dict() for e in (self.case.entities or [])]

        playbook_actions = []
        for run in (self.case.playbook_runs or []):
            playbook_actions.append({
                "playbook": run.playbook.name,
                "mode": run.mode,
                "status": run.status,
                "steps_taken": len([s for s in run.steps_log if s.get("status") == "executed"]),
                "started_at": run.started_at.isoformat() if run.started_at else None,
            })

        nist = NistMapper(self.case).generate_mapping()

        return {
            "report_type": "incident_report",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "generated_by": self.user.email,
            "case": {
                "id": self.case.id,
                "title": self.case.title,
                "severity": self.case.severity,
                "status": self.case.status,
                "created_at": self.case.created_at.isoformat() if self.case.created_at else None,
                "description": self.case.description,
            },
            "executive_summary": analysis.get("summary", "(AI analysis unavailable)"),
            "attack_stage": analysis.get("attack_stage", "unknown"),
            "mitre_techniques": analysis.get("mitre_techniques", []),
            "severity_rationale": analysis.get("severity_rationale", ""),
            "entities_involved": entities,
            "timeline": timeline_entries,
            "response_actions": playbook_actions,
            "immediate_actions": analysis.get("immediate_actions", []),
            "investigation_gaps": analysis.get("investigation_gaps", []),
            "nist_coverage": nist.get("covered_categories", []),
            "nist_coverage_pct": nist.get("coverage_pct", 0),
        }

    def audit_packet(self) -> dict:
        from ..models.audit import AuditLog

        audit_entries = AuditLog.query.filter_by(case_id=self.case.id).order_by(
            AuditLog.created_at
        ).all()

        nist = NistMapper(self.case).generate_mapping()

        playbook_runs = []
        for run in (self.case.playbook_runs or []):
            approvals = [a.to_dict() for a in run.approval_requests]
            playbook_runs.append({
                **run.to_dict(),
                "playbook_name": run.playbook.name,
                "approvals": approvals,
                "steps_log": run.steps_log,
            })

        return {
            "report_type": "audit_packet",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "generated_by": self.user.email,
            "case": self.case.to_dict(include_relations=True),
            "audit_trail": [e.to_dict() for e in audit_entries],
            "playbook_executions": playbook_runs,
            "nist_mapping": nist,
            "evidence_chain": [e.to_dict() for e in (self.case.evidence or [])],
            "attestation": {
                "prepared_by": self.user.email,
                "prepared_at": datetime.now(timezone.utc).isoformat(),
                "statement": (
                    f"This audit packet for Case #{self.case.id} was generated by ContainIQ "
                    "from immutable audit log records and represents an accurate account of "
                    "all analyst actions, approvals, and system events during this incident."
                ),
            },
        }

    def export_pdf(self) -> bytes:
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.lib import colors
            from reportlab.platypus import (
                SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
            )
            import io

            buf = io.BytesIO()
            doc = SimpleDocTemplate(buf, pagesize=letter,
                                    leftMargin=inch, rightMargin=inch,
                                    topMargin=inch, bottomMargin=inch)
            styles = getSampleStyleSheet()
            story = []

            DARK = colors.HexColor("#0d1117")
            ACCENT = colors.HexColor("#0d6efd")

            title_style = ParagraphStyle("title", parent=styles["Title"],
                                         textColor=ACCENT, fontSize=18)
            h2_style = ParagraphStyle("h2", parent=styles["Heading2"],
                                      textColor=DARK, fontSize=13)

            # Header
            story.append(Paragraph("ContainIQ — Incident Report", title_style))
            story.append(Spacer(1, 0.1 * inch))
            story.append(HRFlowable(width="100%", thickness=1, color=ACCENT))
            story.append(Spacer(1, 0.2 * inch))

            report = self.incident_report()

            # Case info table
            case_data = [
                ["Case ID", f"#{self.case.id}"],
                ["Title", self.case.title],
                ["Severity", self.case.severity.upper()],
                ["Status", self.case.status],
                ["Created", self.case.created_at.strftime("%Y-%m-%d %H:%M UTC")
                 if self.case.created_at else ""],
                ["Generated", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")],
            ]
            t = Table(case_data, colWidths=[1.8 * inch, 4.7 * inch])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e9ecef")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("PADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(t)
            story.append(Spacer(1, 0.3 * inch))

            # Executive summary
            story.append(Paragraph("Executive Summary", h2_style))
            story.append(Paragraph(report.get("executive_summary", ""), styles["BodyText"]))
            story.append(Spacer(1, 0.2 * inch))

            # Timeline
            if self.case.timeline:
                story.append(Paragraph("Incident Timeline", h2_style))
                tl_data = [["Time (UTC)", "Type", "Description"]]
                for t_ev in self.case.timeline[:20]:
                    tl_data.append([
                        t_ev.event_time.strftime("%Y-%m-%d %H:%M"),
                        t_ev.event_type or "",
                        Paragraph(t_ev.description[:120], styles["BodyText"]),
                    ])
                tl = Table(tl_data, colWidths=[1.4 * inch, 1.2 * inch, 3.9 * inch])
                tl.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("PADDING", (0, 0), (-1, -1), 5),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8f9fa")]),
                ]))
                story.append(tl)
                story.append(Spacer(1, 0.2 * inch))

            # NIST coverage
            nist = NistMapper(self.case).generate_mapping()
            story.append(Paragraph(
                f"NIST CSF 2.0 Coverage: {nist.get('coverage_pct', 0)}%", h2_style
            ))
            covered_str = ", ".join(nist.get("covered_categories", [])) or "None"
            story.append(Paragraph(f"<b>Covered:</b> {covered_str}", styles["BodyText"]))
            story.append(Spacer(1, 0.3 * inch))

            # Attestation
            story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
            story.append(Spacer(1, 0.1 * inch))
            story.append(Paragraph(
                f"Generated by ContainIQ · {report['generated_by']} · "
                f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
                ParagraphStyle("footer", parent=styles["Normal"], fontSize=8,
                               textColor=colors.grey)
            ))

            doc.build(story)
            return buf.getvalue()

        except ImportError:
            return b"ReportLab not installed. Run: pip install reportlab"
